apiVersion: v1
kind: Service
metadata:
 name: my-cluster-kafka-bootstrap
spec:
 ports:
 - port: 9092
   protocol: TCP
   targetPort: 9092
 selector:
   app: kafka
 type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: kafka
 labels:
  app.openshift.io/runtime: amq
spec:
 selector:
   matchLabels:
     app: kafka
 template:
   metadata:
     labels:
       app: kafka
   spec:
     containers:
     - name: kafka
       image: quay.io/strimzi/kafka:latest-kafka-3.7.0
       command:
         - /bin/sh
         - -c
         - 'export CLUSTER_ID=$(./bin/kafka-storage.sh random-uuid) && ./bin/kafka-storage.sh format -t $CLUSTER_ID -c ./config/kraft/server.properties && ./bin/kafka-server-start.sh ./config/kraft/server.properties --override advertised.listeners=${KAFKA_ADVERTISED_LISTENERS}'
       env:
       - name: LOG_DIR
         value: /tmp/logs
       - name: KAFKA_ADVERTISED_LISTENERS
         value: PLAINTEXT://my-cluster-kafka-bootstrap:9092
       resources:
         limits:
           memory: "1024Mi"
           cpu: "1000m"
       ports:
       - containerPort: 9092
